add solution fo histogram
js-tasks-ru/htmlcss-20231222_konstantinrazin pull request #10
Opened 2024-01-23 13:38 UTC by modemyc

2024-01-23 13:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-25 21:41 UTC, GSemikozov requested changes

2024-01-25 21:41 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__column-basic {
просто .histogram__column

2024-01-25 21:41 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
лишнее

2024-01-25 21:41 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-family: Inter;
чтобы везде не дублировать, проще сразу на уровне блока задать

2024-01-27 14:14 UTC, GSemikozov requested changes

2024-01-27 14:14 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    opacity: 0.8;
кажется, что полупрозрачным делать весь блок - не надо)

2024-01-27 14:14 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__viewer">View all</div>
`<a>`

2024-01-28 16:58 UTC, GSemikozov approved these changes

2024-01-28 16:58 UTC, merged