5 calendar
js-tasks-ru/htmlcss-20231222_konstantinrazin pull request #15
Opened 2024-02-02 11:48 UTC by modemyc

2024-02-02 11:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-02 15:16 UTC, GSemikozov requested changes

2024-02-02 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 26px;
`28 26 32`

2024-02-02 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-rows: 20px;
лишнее, да и не за чем было отделять от общего грида) но раз уж отделили, то сам по себе grid-template-rows здесь бессмысленный

2024-02-02 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-rows: 20px;
лучше на уровне элемента внутри

2024-02-02 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    grid-template-rows: repeat(5, 36px);
лишнее (почему мы делали вариант с ризиновым квадратом - как раз чтобы избежать необходимости растягивать дочерние элементы прописывая им конкретные размеры или фиксированные паддинги)

2024-02-02 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +                <p class="calendar__text">Mon</p>
div

2024-02-02 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/index.html
> +                <p class="calendar__date"></p>
div

2024-02-06 16:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-06 16:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-06 21:27 UTC, GSemikozov approved these changes

2024-02-06 21:27 UTC, merged