add solution for checkbox
js-tasks-ru/htmlcss-20231222_konstantinrazin pull request #21
Opened 2024-04-23 17:37 UTC by modemyc

2024-04-23 17:38 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-25 16:31 UTC, GSemikozov requested changes

2024-04-25 16:31 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkboxes {
это обертка, не относится к данному блоку, удалим

2024-04-25 16:31 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    stroke-width: 3px;
а зачем? проще использовать currentColor + color)

2024-04-25 16:31 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +/*мне показался такой вариант интереснее,
именно так и должно быть

2024-04-25 17:10 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-26 06:50 UTC, GSemikozov requested changes

2024-04-26 06:50 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__control:checked {
а это для чего? у .checkbox__control нет отдельного состояния checked )

2024-04-29 11:26 UTC, GSemikozov approved these changes

2024-04-29 11:26 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-04-29 11:31 UTC, GSemikozov approved these changes

2024-04-29 11:31 UTC, merged