3 button
js-tasks-ru/htmlcss-20231222_konstantinrazin pull request #7
Opened 2024-01-15 11:59 UTC by modemyc

fixed

2024-01-15 12:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-15 22:20 UTC, GSemikozov requested changes

2024-01-15 22:20 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-family: Roboto, sans-serif;
не хватает паддингов

2024-01-19 11:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-19 12:55 UTC, GSemikozov approved these changes

2024-01-19 12:56 UTC, merged