3 accordion
js-tasks-ru/htmlcss-20231222_konstantinrazin pull request #8
Opened 2024-01-15 14:37 UTC by modemyc

добавил решение для задания Аккордеон

2024-01-15 14:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-15 22:21 UTC, GSemikozov requested changes

2024-01-15 22:21 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary_text {
это не модификатор, а элемент, поэтому - .accordion__text

2024-01-17 11:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-17 11:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-01-17 12:18 UTC, GSemikozov approved these changes

2024-01-17 12:19 UTC, merged